### ISSUE TITLE
Bisquare Function

### ISSUE THREAD

**Issue by marcofaga** [cran/btb#1]
Hi. Congrats for the package!

I just have a litle question: which is the kernel bisquare function? Could you provide me the equation?

Many thanks!

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors and possibly URLs in the `DESCRIPTION` file. Thanks!

**Comment by marcofaga** [comment]
Oh sorry. Thanks!!
